package Vista;

import Controlador.ControladorReparacion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Antonio
 */
public class AnadirReparacion extends javax.swing.JDialog {

    private ControladorReparacion miControlador;
    /**
     * Creates new form Reparacion
     */
    public AnadirReparacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miControlador = new ControladorReparacion(this);
        jLabelFondo.setIcon(new ImageIcon("Imagenes/liberacion.jpg"));
        jButtonAceptar.setIcon(new ImageIcon("Imagenes/icon/aceptarnormal.png"));
        jButtonAceptar.setRolloverIcon(new ImageIcon("Imagenes/icon/aceptarrollover.png"));
        jButtonAceptar.setPressedIcon(new ImageIcon("Imagenes/icon/aceptarpressed.png"));
        jButtonBorrar.setIcon(new ImageIcon("Imagenes/icon/eliminarnormal.png"));
        jButtonBorrar.setRolloverIcon(new ImageIcon("Imagenes/icon/eliminarrollover.png"));
        jButtonBorrar.setPressedIcon(new ImageIcon("Imagenes/icon/eliminarpressed.png"));
        jButtonVolverAtras.setIcon(new ImageIcon("Imagenes/icon/backnormal.png"));
        jButtonVolverAtras.setRolloverIcon(new ImageIcon("Imagenes/icon/backrollover.png"));
        jButtonVolverAtras.setPressedIcon(new ImageIcon("Imagenes/icon/backpressed.png"));
       
        try {
            miControlador.cargarProveedores();
        } catch (Exception ex) {
            mostrarError("Ha ocurrido un error al cargar los proveedores.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistroReparacion = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelObservaciones = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jScrollPaneObservaciones = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jButtonAceptar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jComboBoxProveedores = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistroReparacion.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabelRegistroReparacion.setForeground(new java.awt.Color(0, 0, 51));
        jLabelRegistroReparacion.setText("    Registro Reparación");
        getContentPane().add(jLabelRegistroReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 290, -1));

        jLabelProveedor.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabelProveedor.setForeground(new java.awt.Color(0, 0, 51));
        jLabelProveedor.setText("Proveedor:");
        getContentPane().add(jLabelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 20));

        jLabelMarca.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(0, 0, 51));
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 20));

        jLabelModelo.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabelModelo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelModelo.setText("Modelo:");
        getContentPane().add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 60, 20));

        jLabelObservaciones.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabelObservaciones.setForeground(new java.awt.Color(0, 0, 51));
        jLabelObservaciones.setText("Observaciones:");
        getContentPane().add(jLabelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 241, -1));
        getContentPane().add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 241, -1));

        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setRows(5);
        jScrollPaneObservaciones.setViewportView(jTextAreaObservaciones);

        getContentPane().add(jScrollPaneObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 241, 150));

        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAceptar.setToolTipText("Aceptar");
        jButtonAceptar.setBorder(null);
        jButtonAceptar.setBorderPainted(false);
        jButtonAceptar.setContentAreaFilled(false);
        jButtonAceptar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonAceptar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 98, 80));

        jButtonBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBorrar.setToolTipText("Borrar Todo");
        jButtonBorrar.setBorder(null);
        jButtonBorrar.setBorderPainted(false);
        jButtonBorrar.setContentAreaFilled(false);
        jButtonBorrar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonBorrar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonBorrar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 98, 80));

        jButtonVolverAtras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVolverAtras.setToolTipText("Salir");
        jButtonVolverAtras.setBorder(null);
        jButtonVolverAtras.setBorderPainted(false);
        jButtonVolverAtras.setContentAreaFilled(false);
        jButtonVolverAtras.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonVolverAtras.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonVolverAtras.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 98, 80));

        getContentPane().add(jComboBoxProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 240, -1));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try {
            if(miControlador.añadirReparacion())
                mostrarMensaje("La liberación se ha generado correctamente.\n\nPodrás pasar a recogerlo cuando en tus pedidos el estado sea 'Reparado'.");
            else
                mostrarError("No se ha podido generar la reparación.");
        } catch (Exception ex) {
            mostrarError("Ha ocurrido un error al generar la reparación.");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
      
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jTextAreaObservaciones.setText("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed
        
          this.dispose();
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    public JComboBox<String> getjComboBoxProveedores() {
        return jComboBoxProveedores;
    }

    public JTextArea getjTextAreaObservaciones() {
        return jTextAreaObservaciones;
    }

    public JTextField getjTextFieldMarca() {
        return jTextFieldMarca;
    }

    public JTextField getjTextFieldModelo() {
        return jTextFieldModelo;
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.DEFAULT_OPTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnadirReparacion dialog = new AnadirReparacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JComboBox<String> jComboBoxProveedores;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelRegistroReparacion;
    private javax.swing.JScrollPane jScrollPaneObservaciones;
    private javax.swing.JTextArea jTextAreaObservaciones;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
}
