/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Antonio
 */
public class GestionGestores extends javax.swing.JDialog {

    /**
     * Creates new form GestionProveedores
     */
    public GestionGestores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelFondo.setIcon(new ImageIcon("Imagenes/FondoGestionGestores.png"));
        jButtonVolverAtras.setIcon(new ImageIcon("Imagenes/icon/botonvolver.png"));
        jButtonVolverAtras.setPressedIcon(new ImageIcon("Imagenes/icon/botonvolver80%.png"));
        jButtonVolverAtras.setRolloverIcon(new ImageIcon("Imagenes/icon/botonvolver120%.png"));
        jButtonAceptar.setIcon(new ImageIcon("Imagenes/icon/botonaceptar2.png"));
        jButtonAceptar.setPressedIcon(new ImageIcon("Imagenes/icon/botonaceptar4.png"));
        jButtonAceptar.setRolloverIcon(new ImageIcon("Imagenes/icon/botonaceptar3.png"));
        jButtonBorrarCampos.setIcon(new ImageIcon("Imagenes/icon/borrar1.png"));
        jButtonBorrarCampos.setPressedIcon(new ImageIcon("Imagenes/icon/borrar3.png"));
        jButtonBorrarCampos.setRolloverIcon(new ImageIcon("Imagenes/icon/borrar2.png"));
        setLocationRelativeTo(null);
        jLabelTipoGestor.setVisible(false);
        jLabelNombreGestor.setVisible(false);
        jLabelDireccionGestor.setVisible(false);
        jLabelTelefonoGestor.setVisible(false);
        jLabelEmailGestor.setVisible(false);
        jComboBoxTipoGestor.setVisible(false);
        jTextFieldNombreGestor.setVisible(false);
        jTextFieldDireccionGestor.setVisible(false);
        jTextFieldTelefonoGestor.setVisible(false);
        jTextFieldEmailGestor.setVisible(false);
        jButtonAceptar.setVisible(false);
        jLabelGestor.setVisible(false);
        jComboBoxGestores.setVisible(false);
        jButtonBorrarCampos.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInsertarGestor = new javax.swing.JButton();
        jButtonModificarGestor = new javax.swing.JButton();
        jButtonEliminarGestor = new javax.swing.JButton();
        jComboBoxTipoGestor = new javax.swing.JComboBox<>();
        jLabelTipoGestor = new javax.swing.JLabel();
        jLabelNombreGestor = new javax.swing.JLabel();
        jTextFieldNombreGestor = new javax.swing.JTextField();
        jTextFieldDireccionGestor = new javax.swing.JTextField();
        jLabelDireccionGestor = new javax.swing.JLabel();
        jLabelTelefonoGestor = new javax.swing.JLabel();
        jTextFieldTelefonoGestor = new javax.swing.JTextField();
        jLabelEmailGestor = new javax.swing.JLabel();
        jTextFieldEmailGestor = new javax.swing.JTextField();
        jButtonVolverAtras = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabelGestor = new javax.swing.JLabel();
        jComboBoxGestores = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonBorrarCampos = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(760, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInsertarGestor.setText("Añadir gestor");
        jButtonInsertarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarGestorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertarGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 50));

        jButtonModificarGestor.setText("Modificar gestor");
        jButtonModificarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarGestorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, 50));

        jButtonEliminarGestor.setText("Eliminar gestor");
        jButtonEliminarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarGestorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 50));

        jComboBoxTipoGestor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor", "Operador" }));
        getContentPane().add(jComboBoxTipoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 173, -1));

        jLabelTipoGestor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoGestor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoGestor.setText("Tipo gestor: ");
        getContentPane().add(jLabelTipoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 90, -1));

        jLabelNombreGestor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombreGestor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreGestor.setText("Nombre: ");
        getContentPane().add(jLabelNombreGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 70, 20));
        getContentPane().add(jTextFieldNombreGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 170, -1));
        getContentPane().add(jTextFieldDireccionGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 170, -1));

        jLabelDireccionGestor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDireccionGestor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccionGestor.setText("Direccion: ");
        getContentPane().add(jLabelDireccionGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 20));

        jLabelTelefonoGestor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTelefonoGestor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoGestor.setText("Telefono: ");
        getContentPane().add(jLabelTelefonoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 70, 20));
        getContentPane().add(jTextFieldTelefonoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, -1));

        jLabelEmailGestor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEmailGestor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailGestor.setText("Email: ");
        getContentPane().add(jLabelEmailGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, 20));
        getContentPane().add(jTextFieldEmailGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 170, -1));

        jButtonVolverAtras.setToolTipText("Volver atras");
        jButtonVolverAtras.setBorder(null);
        jButtonVolverAtras.setBorderPainted(false);
        jButtonVolverAtras.setContentAreaFilled(false);
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 90, 90));

        jButtonAceptar.setToolTipText("Aceptar");
        jButtonAceptar.setBorder(null);
        jButtonAceptar.setBorderPainted(false);
        jButtonAceptar.setContentAreaFilled(false);
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 90, 90));

        jLabelGestor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGestor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestor.setText("Gestor:");
        getContentPane().add(jLabelGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, -1));

        jComboBoxGestores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGestoresActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxGestores, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 170, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Gestores");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 160, 50));

        jButtonBorrarCampos.setToolTipText("Borrar datos");
        jButtonBorrarCampos.setBorder(null);
        jButtonBorrarCampos.setBorderPainted(false);
        jButtonBorrarCampos.setContentAreaFilled(false);
        jButtonBorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 90, 90));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonInsertarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarGestorActionPerformed
        // TODO add your handling code here:
        
        jLabelTipoGestor.setVisible(true);
        jLabelNombreGestor.setVisible(true);
        jLabelDireccionGestor.setVisible(true);
        jLabelTelefonoGestor.setVisible(true);
        jLabelEmailGestor.setVisible(true);
        jComboBoxTipoGestor.setVisible(true);
        jTextFieldNombreGestor.setVisible(true);
        jTextFieldDireccionGestor.setVisible(true);
        jTextFieldTelefonoGestor.setVisible(true);
        jTextFieldEmailGestor.setVisible(true);
        jButtonAceptar.setVisible(true);
        jLabelGestor.setVisible(false);
        jComboBoxGestores.setVisible(false);
        jButtonBorrarCampos.setVisible(true);
    }//GEN-LAST:event_jButtonInsertarGestorActionPerformed

    private void jComboBoxGestoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGestoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGestoresActionPerformed

    private void jButtonModificarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarGestorActionPerformed
        // TODO add your handling code here:
        jLabelTipoGestor.setVisible(true);
        jLabelNombreGestor.setVisible(true);
        jLabelDireccionGestor.setVisible(true);
        jLabelTelefonoGestor.setVisible(true);
        jLabelEmailGestor.setVisible(true);
        jComboBoxTipoGestor.setVisible(true);
        jTextFieldNombreGestor.setVisible(true);
        jTextFieldDireccionGestor.setVisible(true);
        jTextFieldTelefonoGestor.setVisible(true);
        jTextFieldEmailGestor.setVisible(true);
        jButtonAceptar.setVisible(true);
        jLabelGestor.setVisible(true);
        jComboBoxGestores.setVisible(true);
        jButtonBorrarCampos.setVisible(true);
    }//GEN-LAST:event_jButtonModificarGestorActionPerformed

    private void jButtonEliminarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarGestorActionPerformed
        // TODO add your handling code here:
        jLabelTipoGestor.setVisible(true);
        jLabelNombreGestor.setVisible(true);
        jLabelDireccionGestor.setVisible(true);
        jLabelTelefonoGestor.setVisible(true);
        jLabelEmailGestor.setVisible(true);
        jComboBoxTipoGestor.setVisible(true);
        jTextFieldNombreGestor.setVisible(true);
        jTextFieldDireccionGestor.setVisible(true);
        jTextFieldTelefonoGestor.setVisible(true);
        jTextFieldEmailGestor.setVisible(true);
        jButtonAceptar.setVisible(true);
        jLabelGestor.setVisible(true);
        jComboBoxGestores.setVisible(true);
        jButtonBorrarCampos.setVisible(true);
    }//GEN-LAST:event_jButtonEliminarGestorActionPerformed

    private void jButtonBorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCamposActionPerformed
        // TODO add your handling code here:
        
        
        jTextFieldNombreGestor.setText("");
        jTextFieldDireccionGestor.setText("");
        jTextFieldTelefonoGestor.setText("");
        jTextFieldEmailGestor.setText("");
        jComboBoxGestores.setModel(new DefaultComboBoxModel());
    }//GEN-LAST:event_jButtonBorrarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionGestores dialog = new GestionGestores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBorrarCampos;
    private javax.swing.JButton jButtonEliminarGestor;
    private javax.swing.JButton jButtonInsertarGestor;
    private javax.swing.JButton jButtonModificarGestor;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JComboBox<String> jComboBoxGestores;
    private javax.swing.JComboBox<String> jComboBoxTipoGestor;
    private javax.swing.JLabel jLabelDireccionGestor;
    private javax.swing.JLabel jLabelEmailGestor;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGestor;
    private javax.swing.JLabel jLabelNombreGestor;
    private javax.swing.JLabel jLabelTelefonoGestor;
    private javax.swing.JLabel jLabelTipoGestor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldDireccionGestor;
    private javax.swing.JTextField jTextFieldEmailGestor;
    private javax.swing.JTextField jTextFieldNombreGestor;
    private javax.swing.JTextField jTextFieldTelefonoGestor;
    // End of variables declaration//GEN-END:variables
}
