/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.Color;


/**
 *
 * @author Antonio
 */
public class GestionAdministrador extends javax.swing.JDialog {

    /**
     * Creates new form GestionAdministrador
     */
    public GestionAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanelPrincipal.setVisible(true);
        //jPanelPrincipal.setBackground(new Color(0,0,0,255));
        //jPanelUsuarios.setBackground(new Color(0,0,0,255));
        //jPanelModificarUsuario.setBackground(new Color(0,0,0,255));
        //jPanelUsuarios.setVisible(false);
        setLocationRelativeTo(null);
    
        
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouppermisos = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonLiberacion = new javax.swing.JButton();
        jButtonReparacion = new javax.swing.JButton();
        jButtonGestionUsuarios = new javax.swing.JButton();
        jButtonGestionPedidos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelUsuarios = new javax.swing.JPanel();
        jButtonModificarUsuario = new javax.swing.JButton();
        jButtonEliminarUsuario = new javax.swing.JButton();
        jButtonInsertarUsuario = new javax.swing.JButton();
        jLabelLiberaciones = new javax.swing.JLabel();
        jLabelImei = new javax.swing.JLabel();
        jComboBoxOperadores = new javax.swing.JComboBox<>();
        jLabelOperador = new javax.swing.JLabel();
        jTextFieldImei = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jLabelNombreCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabelObservaciones = new javax.swing.JLabel();
        jTextFieldObservaciones = new javax.swing.JTextField();
        jLabelDiagnostico = new javax.swing.JLabel();
        jScrollPaneDiagnostico = new javax.swing.JScrollPane();
        jTextAreaDiagnostico = new javax.swing.JTextArea();
        jPanelModificarUsuario = new javax.swing.JPanel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jTextFieldBuscadorId = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelNacimiento = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jDateChooserNacimiento = new com.toedter.calendar.JDateChooser();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonCambiar = new javax.swing.JButton();
        jButtonBorrarTodo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelPermisos = new javax.swing.JLabel();
        jRadioButtonAdministrador = new javax.swing.JRadioButton();
        jRadioButtonInvitado = new javax.swing.JRadioButton();
        jRadioButtonCliente = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSolicitarCodigo = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondoUsuario = new javax.swing.JLabel();
        jLabelFondoPrincipal = new javax.swing.JLabel();
        jLabelfondoprincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion del Administrador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setOpaque(false);
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLiberacion.setText("Realizar Liberacion");
        jButtonLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiberacionActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButtonLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 60));

        jButtonReparacion.setText("Realizar Reparacion");
        jButtonReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReparacionActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButtonReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 60));

        jButtonGestionUsuarios.setText("Gestion de usuarios");
        jButtonGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionUsuariosActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButtonGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 60));

        jButtonGestionPedidos.setText("Gestion de pedidos");
        jPanelPrincipal.add(jButtonGestionPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 60));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 453, 160, 80));

        jPanelUsuarios.setOpaque(false);
        jPanelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificarUsuario.setText("Modificar usuario");
        jButtonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarUsuarioActionPerformed(evt);
            }
        });
        jPanelUsuarios.add(jButtonModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 130, 70));

        jButtonEliminarUsuario.setText("Eliminar usuario");
        jButtonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanelUsuarios.add(jButtonEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 70));

        jButtonInsertarUsuario.setText("Añadir usuario");
        jButtonInsertarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarUsuarioActionPerformed(evt);
            }
        });
        jPanelUsuarios.add(jButtonInsertarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 283, 130, 70));

        jLabelLiberaciones.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelLiberaciones.setText("LIBERACIONES");
        jPanelUsuarios.add(jLabelLiberaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 210, 57));

        jLabelImei.setText("IMEI del terminal: ");
        jPanelUsuarios.add(jLabelImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jComboBoxOperadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movistar", "Vodafone", "Orange", "Yoigo", " " }));
        jComboBoxOperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperadoresActionPerformed(evt);
            }
        });
        jPanelUsuarios.add(jComboBoxOperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 200, -1));

        jLabelOperador.setText("Operador: ");
        jPanelUsuarios.add(jLabelOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 87, -1));
        jPanelUsuarios.add(jTextFieldImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 200, -1));

        jButtonBack.setText("Volver atras");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanelUsuarios.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 403, 130, 40));

        jLabelNombreCliente.setText("Nombre del cliente: ");
        jPanelUsuarios.add(jLabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 120, 20));
        jPanelUsuarios.add(jTextFieldNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 200, -1));

        jLabelObservaciones.setText("Observaciones: ");
        jPanelUsuarios.add(jLabelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 90, -1));
        jPanelUsuarios.add(jTextFieldObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 200, -1));

        jLabelDiagnostico.setText("Diagnostico: ");
        jPanelUsuarios.add(jLabelDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jTextAreaDiagnostico.setColumns(20);
        jTextAreaDiagnostico.setRows(5);
        jScrollPaneDiagnostico.setViewportView(jTextAreaDiagnostico);

        jPanelUsuarios.add(jScrollPaneDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 320, 130));

        jPanelModificarUsuario.setMinimumSize(new java.awt.Dimension(481, 590));
        jPanelModificarUsuario.setOpaque(false);
        jPanelModificarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIdUsuario.setText("Id: ");
        jPanelModificarUsuario.add(jLabelIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 30, 29, 26));

        jTextFieldBuscadorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscadorIdActionPerformed(evt);
            }
        });
        jPanelModificarUsuario.add(jTextFieldBuscadorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 33, 115, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanelModificarUsuario.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 32, -1, -1));

        jLabelNombre.setText("Nombre: ");
        jPanelModificarUsuario.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 77, -1, -1));

        jLabelApellidos.setText("Apellidos: ");
        jPanelModificarUsuario.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 108, -1, -1));

        jLabelDni.setText("DNI: ");
        jPanelModificarUsuario.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 146, -1, -1));

        jLabelNacimiento.setText("Fecha Nacimiento: ");
        jPanelModificarUsuario.add(jLabelNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 181, -1, -1));

        jLabelDireccion.setText("Dirección: ");
        jPanelModificarUsuario.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 219, -1, -1));

        jLabelTelefono.setText("Telefono: ");
        jPanelModificarUsuario.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 263, -1, -1));
        jPanelModificarUsuario.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 74, 179, -1));
        jPanelModificarUsuario.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 105, 179, -1));
        jPanelModificarUsuario.add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 143, 179, -1));

        jDateChooserNacimiento.setFocusable(false);
        jPanelModificarUsuario.add(jDateChooserNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 181, 179, -1));
        jPanelModificarUsuario.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 219, 180, -1));
        jPanelModificarUsuario.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 260, 180, -1));

        jButtonCambiar.setText("Realizar cambios");
        jPanelModificarUsuario.add(jButtonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 500, -1, -1));

        jButtonBorrarTodo.setText("Borrar todo");
        jButtonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodoActionPerformed(evt);
            }
        });
        jPanelModificarUsuario.add(jButtonBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 500, -1, -1));

        jButtonCancelar.setText("Volver atras");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelModificarUsuario.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        jLabelUsuario.setText("Usuario: ");
        jPanelModificarUsuario.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 301, -1, -1));

        jLabelPassword.setText("Contraseña: ");
        jPanelModificarUsuario.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 339, -1, -1));
        jPanelModificarUsuario.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 298, 180, -1));
        jPanelModificarUsuario.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 336, 180, -1));

        jLabelPermisos.setText("Permisos: ");
        jPanelModificarUsuario.add(jLabelPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 384, -1, -1));

        buttonGrouppermisos.add(jRadioButtonAdministrador);
        jRadioButtonAdministrador.setText("Administrador");
        jRadioButtonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdministradorActionPerformed(evt);
            }
        });
        jPanelModificarUsuario.add(jRadioButtonAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        buttonGrouppermisos.add(jRadioButtonInvitado);
        jRadioButtonInvitado.setText("Invitado");
        jPanelModificarUsuario.add(jRadioButtonInvitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        buttonGrouppermisos.add(jRadioButtonCliente);
        jRadioButtonCliente.setText("Cliente");
        jPanelModificarUsuario.add(jRadioButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));
        jPanelModificarUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        jPanelUsuarios.add(jPanelModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 600, 590));

        jButtonSolicitarCodigo.setText("Solicitar Código");
        jPanelUsuarios.add(jButtonSolicitarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jButtonVolver.setText("Volver Atrás");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelUsuarios.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));
        jPanelUsuarios.add(jLabelFondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 590));

        jPanelPrincipal.add(jPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 760, 590));
        jPanelPrincipal.add(jLabelFondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        jLabelfondoprincipal.setOpaque(true);
        getContentPane().add(jLabelfondoprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionUsuariosActionPerformed
        // TODO add your handling code here:

        jPanelUsuarios.setVisible(true);
        jButtonModificarUsuario.setVisible(true);
        jButtonEliminarUsuario.setVisible(true);
        jButtonInsertarUsuario.setVisible(true);
        jButtonBack.setVisible(true);
        jPanelModificarUsuario.setVisible(false);
        jLabelLiberaciones.setVisible(false);
        jLabelImei.setVisible(false);
        jComboBoxOperadores.setVisible(false);
        jLabelOperador.setVisible(false);
        jButtonSolicitarCodigo.setVisible(false);
        jButtonVolver.setVisible(false);
        jTextFieldImei.setVisible(false);
        jLabelNombreCliente.setVisible(false);
        jTextFieldNombreCliente.setVisible(false);
        jLabelObservaciones.setVisible(false);
        jTextFieldObservaciones.setVisible(false);
        jLabelDiagnostico.setVisible(false);
        jTextAreaDiagnostico.setVisible(false);
        jScrollPaneDiagnostico.setVisible(false);
        jButtonSolicitarCodigo.setVisible(false);


    }//GEN-LAST:event_jButtonGestionUsuariosActionPerformed

    private void jTextFieldBuscadorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscadorIdActionPerformed

    private void jButtonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarUsuarioActionPerformed
        // TODO add your handling code here:
        jPanelModificarUsuario.setVisible(true);
        jLabelIdUsuario.setVisible(true);
        jTextFieldBuscadorId.setVisible(true);
        jButtonBuscar.setVisible(true);
        jLabelNombre.setVisible(false);
        jLabelApellidos.setVisible(false);
        jLabelDni.setVisible(false);
        jLabelDireccion.setVisible(false);
        jLabelTelefono.setVisible(false);
        jLabelNacimiento.setVisible(false);
        jLabelUsuario.setVisible(false);
        jLabelPassword.setVisible(false);
        jTextFieldNombre.setVisible(false);
        jTextFieldApellidos.setVisible(false);
        jTextFieldDni.setVisible(false);
        jDateChooserNacimiento.setVisible(false);
        jTextFieldDireccion.setVisible(false);
        jTextFieldTelefono.setVisible(false);
        jTextFieldUsuario.setVisible(false);
        jTextFieldPassword.setVisible(false);
        jButtonCambiar.setVisible(false);
        jButtonBorrarTodo.setVisible(false);
        jButtonCancelar.setVisible(false);
        jLabelPermisos.setVisible(false);
        jRadioButtonCliente.setVisible(false);
        jRadioButtonInvitado.setVisible(false);
        jRadioButtonAdministrador.setVisible(false);
        jButtonCambiar.setVisible(false);
        jButtonBorrarTodo.setVisible(false);
        jButtonCancelar.setVisible(false);


    }//GEN-LAST:event_jButtonModificarUsuarioActionPerformed

    private void jButtonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodoActionPerformed
        // TODO add your handling code here:

        jTextFieldNombre.setText("");
        jTextFieldApellidos.setText("");
        jTextFieldDni.setText("");
        jDateChooserNacimiento.setDate(null);
        jTextFieldDireccion.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldUsuario.setText("");
        jTextFieldPassword.setText("");
    }//GEN-LAST:event_jButtonBorrarTodoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jPanelModificarUsuario.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:

        jLabelNombre.setVisible(true);
        jLabelApellidos.setVisible(true);
        jLabelDni.setVisible(true);
        jLabelDireccion.setVisible(true);
        jLabelTelefono.setVisible(true);
        jLabelNacimiento.setVisible(true);
        jLabelUsuario.setVisible(true);
        jLabelPassword.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jTextFieldApellidos.setVisible(true);
        jTextFieldDni.setVisible(true);
        jDateChooserNacimiento.setVisible(true);
        jTextFieldDireccion.setVisible(true);
        jTextFieldTelefono.setVisible(true);
        jTextFieldUsuario.setVisible(true);
        jTextFieldPassword.setVisible(true);
        jButtonCambiar.setVisible(true);
        jButtonBorrarTodo.setVisible(true);
        jButtonCancelar.setVisible(true);
        jLabelPermisos.setVisible(true);
        jRadioButtonCliente.setVisible(true);
        jRadioButtonInvitado.setVisible(true);
        jRadioButtonAdministrador.setVisible(true);

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonInsertarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarUsuarioActionPerformed
        // TODO add your handling code here:
        jPanelModificarUsuario.setVisible(true);
        jLabelIdUsuario.setVisible(false);
        jTextFieldBuscadorId.setVisible(false);
        jButtonBuscar.setVisible(false);
        jLabelNombre.setVisible(true);
        jLabelApellidos.setVisible(true);
        jLabelDni.setVisible(true);
        jLabelDireccion.setVisible(true);
        jLabelTelefono.setVisible(true);
        jLabelNacimiento.setVisible(true);
        jLabelUsuario.setVisible(true);
        jLabelPassword.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jTextFieldApellidos.setVisible(true);
        jTextFieldDni.setVisible(true);
        jDateChooserNacimiento.setVisible(true);
        jTextFieldDireccion.setVisible(true);
        jTextFieldTelefono.setVisible(true);
        jTextFieldUsuario.setVisible(true);
        jTextFieldPassword.setVisible(true);
        jButtonCambiar.setVisible(true);
        jButtonBorrarTodo.setVisible(true);
        jButtonCancelar.setVisible(true);
        jLabelPermisos.setVisible(true);
        jRadioButtonCliente.setVisible(true);
        jRadioButtonInvitado.setVisible(true);
        jRadioButtonAdministrador.setVisible(true);

    }//GEN-LAST:event_jButtonInsertarUsuarioActionPerformed

    private void jButtonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarUsuarioActionPerformed
        // TODO add your handling code here:

        jPanelModificarUsuario.setVisible(true);
        jLabelIdUsuario.setVisible(true);
        jTextFieldBuscadorId.setVisible(true);
        jButtonBuscar.setVisible(true);
        jLabelNombre.setVisible(false);
        jLabelApellidos.setVisible(false);
        jLabelDni.setVisible(false);
        jLabelDireccion.setVisible(false);
        jLabelTelefono.setVisible(false);
        jLabelNacimiento.setVisible(false);
        jLabelUsuario.setVisible(false);
        jLabelPassword.setVisible(false);
        jTextFieldNombre.setVisible(false);
        jTextFieldApellidos.setVisible(false);
        jTextFieldDni.setVisible(false);
        jDateChooserNacimiento.setVisible(false);
        jTextFieldDireccion.setVisible(false);
        jTextFieldTelefono.setVisible(false);
        jTextFieldUsuario.setVisible(false);
        jTextFieldPassword.setVisible(false);
        jButtonCambiar.setVisible(false);
        jButtonBorrarTodo.setVisible(false);
        jButtonCancelar.setVisible(false);
        jLabelPermisos.setVisible(false);
        jRadioButtonCliente.setVisible(false);
        jRadioButtonInvitado.setVisible(false);
        jRadioButtonAdministrador.setVisible(false);

    }//GEN-LAST:event_jButtonEliminarUsuarioActionPerformed

    private void jRadioButtonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAdministradorActionPerformed

    private void jButtonLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiberacionActionPerformed
        // TODO add your handling code here:
        jPanelUsuarios.setVisible(true);
        jLabelNombreCliente.setVisible(false);
        jTextFieldNombreCliente.setVisible(false);
        jLabelObservaciones.setVisible(false);
        jTextFieldObservaciones.setVisible(false);
        jLabelDiagnostico.setVisible(false);
        jTextAreaDiagnostico.setVisible(false);
        jScrollPaneDiagnostico.setVisible(false);
        jButtonSolicitarCodigo.setVisible(false);
        jButtonSolicitarCodigo.setText("Solicitar Codigo");
        jLabelLiberaciones.setText("Liberaciones");
        jLabelLiberaciones.setVisible(true);
        jLabelImei.setVisible(true);
        jComboBoxOperadores.setVisible(true);
        jLabelOperador.setVisible(true);
        jButtonSolicitarCodigo.setVisible(true);
        jButtonVolver.setVisible(true);
        jTextFieldImei.setVisible(true);
        jPanelModificarUsuario.setVisible(false);
        jButtonModificarUsuario.setVisible(false);
        jButtonEliminarUsuario.setVisible(false);
        jButtonInsertarUsuario.setVisible(false);
        jButtonBack.setVisible(false);
    }//GEN-LAST:event_jButtonLiberacionActionPerformed

    private void jComboBoxOperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOperadoresActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        jLabelLiberaciones.setVisible(false);
        jLabelImei.setVisible(false);
        jComboBoxOperadores.setVisible(false);
        jLabelOperador.setVisible(false);
        jButtonSolicitarCodigo.setVisible(false);
        jButtonVolver.setVisible(false);
        jTextFieldImei.setVisible(false);
        jLabelNombreCliente.setVisible(false);
        jTextFieldNombreCliente.setVisible(false);
        jLabelObservaciones.setVisible(false);
        jTextFieldObservaciones.setVisible(false);
        jLabelDiagnostico.setVisible(false);
        jTextAreaDiagnostico.setVisible(false);
        jScrollPaneDiagnostico.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        jPanelUsuarios.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReparacionActionPerformed
        // TODO add your handling code here:
        jPanelUsuarios.setVisible(true);
        jLabelNombreCliente.setVisible(true);
        jTextFieldNombreCliente.setVisible(true);
        jLabelObservaciones.setVisible(true);
        jTextFieldObservaciones.setVisible(true);
        jLabelDiagnostico.setVisible(true);
        jTextAreaDiagnostico.setVisible(true);
        jScrollPaneDiagnostico.setVisible(true);
        jButtonSolicitarCodigo.setVisible(true);
        jButtonSolicitarCodigo.setText("Generar Informe");
        jLabelLiberaciones.setText("Reparaciones");
        jLabelLiberaciones.setVisible(true);
        jButtonVolver.setVisible(true);
        jLabelImei.setVisible(false);
        jComboBoxOperadores.setVisible(false);
        jLabelOperador.setVisible(false);
        jTextFieldImei.setVisible(false);
        jPanelModificarUsuario.setVisible(false);
        jButtonModificarUsuario.setVisible(false);
        jButtonEliminarUsuario.setVisible(false);
        jButtonInsertarUsuario.setVisible(false);
        jButtonBack.setVisible(false);

    }//GEN-LAST:event_jButtonReparacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionAdministrador dialog = new GestionAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrouppermisos;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBorrarTodo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarUsuario;
    private javax.swing.JButton jButtonGestionPedidos;
    private javax.swing.JButton jButtonGestionUsuarios;
    private javax.swing.JButton jButtonInsertarUsuario;
    private javax.swing.JButton jButtonLiberacion;
    private javax.swing.JButton jButtonModificarUsuario;
    private javax.swing.JButton jButtonReparacion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSolicitarCodigo;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxOperadores;
    private com.toedter.calendar.JDateChooser jDateChooserNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDiagnostico;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFondoPrincipal;
    private javax.swing.JLabel jLabelFondoUsuario;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelImei;
    private javax.swing.JLabel jLabelLiberaciones;
    private javax.swing.JLabel jLabelNacimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelOperador;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPermisos;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelfondoprincipal;
    private javax.swing.JPanel jPanelModificarUsuario;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JRadioButton jRadioButtonAdministrador;
    private javax.swing.JRadioButton jRadioButtonCliente;
    private javax.swing.JRadioButton jRadioButtonInvitado;
    private javax.swing.JScrollPane jScrollPaneDiagnostico;
    private javax.swing.JTextArea jTextAreaDiagnostico;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldBuscadorId;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldImei;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldObservaciones;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
