/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorGestionPedidosClientes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Antonio
 */
public class GestionPedidosClientes extends javax.swing.JDialog {

    private ControladorGestionPedidosClientes miControlador;
    /**
     * Creates new form GestionPedidosClientes
     */
    public GestionPedidosClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miControlador = new ControladorGestionPedidosClientes(this);
        miControlador.cargarTodosPedidos();
        jButtonCancelar.setEnabled(false);
        jButtonVolver.setIcon(new ImageIcon("Imagenes/icon/backnormal.png"));;
        jButtonVolver.setPressedIcon(new ImageIcon("Imagenes/icon/backpressed.png"));
        jButtonVolver.setRolloverIcon(new ImageIcon("Imagenes/icon/backrollover.png"));
        jLabelFondo.setIcon(new ImageIcon("Imagenes/pedidoscliente.jpg"));
    }

    public JComboBox<String> getjComboBoxEstadoPedido() {
        return jComboBoxEstadoPedido;
    }

    public JTable getjTablePedidos() {
        return jTablePedidos;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxEstadoPedido = new javax.swing.JComboBox<>();
        jLabelEstados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxEstadoPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Completados", "No completados", "Cancelados" }));
        jComboBoxEstadoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxEstadoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 28, 222, -1));

        jLabelEstados.setText("Estado del pedido:");
        getContentPane().add(jLabelEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 31, -1, -1));

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 75, 749, -1));

        jButtonCancelar.setText("Cancelar pedido");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 130, 52));

        jButtonVolver.setToolTipText("Volver atras");
        jButtonVolver.setBorder(null);
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 533, 97, 73));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 606));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEstadoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoPedidoActionPerformed
        switch(jComboBoxEstadoPedido.getSelectedItem().toString()){
            case "Todos":
                jButtonCancelar.setEnabled(false);
                miControlador.cargarTodosPedidos();
                break;
            case "Completados":
                jButtonCancelar.setEnabled(false);
                miControlador.cargarPedidosCompletados();
                break;
            case "No completados":
                jButtonCancelar.setEnabled(true);
                miControlador.cargarPedidosNoCompletados();
                break;
            case "Cancelados":
                jButtonCancelar.setEnabled(false);
                miControlador.cargarPedidosCancelados();
                break;
        }
    }//GEN-LAST:event_jComboBoxEstadoPedidoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        try {
            miControlador.cancelarPedidos();
        } catch (Exception ex) {
            mostrarError("Ha ocurrido un error al cancelar los pedidos.");
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTablePedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePedidosMouseClicked
        int numeroPedido = 0;
        String tipo = "";
        if(jComboBoxEstadoPedido.getSelectedIndex() != 2){
            if(jTablePedidos.getSelectedColumn() == 6){
                tipo = jTablePedidos.getValueAt(jTablePedidos.getSelectedRow(), 3).toString();
                numeroPedido = Integer.parseInt(jTablePedidos.getValueAt(jTablePedidos.getSelectedRow(), 0).toString());
                try {
                    miControlador.mostrarDetalles(numeroPedido, tipo);
                } catch (Exception ex) {
                    mostrarError("Error al mostrar los detalles del pedido.");
                }
            }
        } else{
            if(jTablePedidos.getSelectedColumn() == 7){
                tipo = jTablePedidos.getValueAt(jTablePedidos.getSelectedRow(), 4).toString();
                numeroPedido = Integer.parseInt(jTablePedidos.getValueAt(jTablePedidos.getSelectedRow(), 1).toString());
                try {
                    miControlador.mostrarDetalles(numeroPedido, tipo);
                } catch (Exception ex) {
                    mostrarError("Error al mostrar los detalles del pedido.");
                }
            }
        }
    }//GEN-LAST:event_jTablePedidosMouseClicked

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.DEFAULT_OPTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPedidosClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPedidosClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPedidosClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPedidosClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionPedidosClientes dialog = new GestionPedidosClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstadoPedido;
    private javax.swing.JLabel jLabelEstados;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedidos;
    // End of variables declaration//GEN-END:variables
}
