package Vista;

import Controlador.ControladorGestionPedidos;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author José Manuel Moreno, Carmen Barranco, Antonio Serrano
 */
public class GestionPedidos extends javax.swing.JDialog {

    private ControladorGestionPedidos miControlador;
    private boolean pendientes;
    /**
     * Creates new form GestionPedidos
     */
    public GestionPedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miControlador = new ControladorGestionPedidos(this);
        jButtonBuscar.setIcon(new ImageIcon("Imagenes/icon/buscarnormal2.png"));
        jButtonBuscar.setRolloverIcon(new ImageIcon("Imagenes/icon/buscarrollover2.png"));
        jButtonBuscar.setPressedIcon(new ImageIcon("Imagenes/icon/buscarpressed2.png"));
        jTextFieldNombreCliente.setVisible(false);
        jLabelNombreCliente.setVisible(false);
        jButtonBuscar.setVisible(false);
        jTablePedidos.setVisible(false);
        jButtonCancelarPedido.setVisible(false);
        jButtonRealizar.setVisible(false);
        jScrollPanePedidos.setVisible(false);
        setLocationRelativeTo(null);
        jButtonVolverAtras.setIcon(new ImageIcon("Imagenes/icon/backnormal.png"));
        jButtonVolverAtras.setPressedIcon(new ImageIcon("Imagenes/icon/backpressed.png"));
        jButtonVolverAtras.setRolloverIcon(new ImageIcon("Imagenes/icon/backrollover.png")); 
        jButtonVolver.setIcon(new ImageIcon("Imagenes/icon/backnormal.png"));
        jButtonVolver.setPressedIcon(new ImageIcon("Imagenes/icon/backpressed.png"));
        jButtonVolver.setRolloverIcon(new ImageIcon("Imagenes/icon/backrollover.png"));
        jButtonVolver.setVisible(false);
        jLabelFondo.setIcon(new ImageIcon("Imagenes/gestionAdmin.jpg"));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonComprobarPedido = new javax.swing.JButton();
        jButtonCancelarPedido = new javax.swing.JButton();
        jButtonListarPedidos = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jLabelNombreCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPanePedidos = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jButtonRealizar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Gestion de Pedidos"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(989, 586));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonComprobarPedido.setText("Comprobar Pedidos Pendientes");
        jButtonComprobarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComprobarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 107, 230, 40));

        jButtonCancelarPedido.setText("Cancelar Pedido");
        jButtonCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 158, 39));

        jButtonListarPedidos.setText("Listar Pedidos");
        jButtonListarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListarPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 230, 39));

        jButtonVolverAtras.setToolTipText("Volver atras");
        jButtonVolverAtras.setBorder(null);
        jButtonVolverAtras.setBorderPainted(false);
        jButtonVolverAtras.setContentAreaFilled(false);
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 90, 90));

        jLabelNombreCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabelNombreCliente.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNombreCliente.setText("Nombre Cliente: ");
        getContentPane().add(jLabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 120, 20));

        jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 169, -1));

        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 70, 60));

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Nº Pedido", "Marca", "Modelo", "Fecha Pedido", "Pedido Realizado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPanePedidos.setViewportView(jTablePedidos);
        if (jTablePedidos.getColumnModel().getColumnCount() > 0) {
            jTablePedidos.getColumnModel().getColumn(0).setResizable(false);
            jTablePedidos.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTablePedidos.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPanePedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 620, 270));

        jButtonRealizar.setText("Realizar Pedido");
        jButtonRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 149, 39));

        jButtonVolver.setToolTipText("Volver atras");
        jButtonVolver.setBorder(null);
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 483, 100, 90));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 989, 586));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprobarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarPedidoActionPerformed
        pendientes = true;
        jTextFieldNombreCliente.setVisible(true);
        jLabelNombreCliente.setVisible(true);
        jButtonBuscar.setVisible(true);
        jTablePedidos.setVisible(false);
        jScrollPanePedidos.setVisible(false);
        jButtonVolver.setVisible(true);
    }//GEN-LAST:event_jButtonComprobarPedidoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(!jTextFieldNombreCliente.getText().equals("")){
            
            if(pendientes){
                
                try {
                    if(miControlador.mostarPendientes()){
                        jButtonCancelarPedido.setVisible(true);
                        jButtonRealizar.setVisible(true);
                        jScrollPanePedidos.setVisible(true);
                        jTablePedidos.setVisible(true);
                    }
                } catch (Exception ex) {
                    mostrarError("Error al mostrar pedidos pendientes del cliente.");
                }
            } else{
                try {
                    if(miControlador.mostrarPedidos()){
                        jScrollPanePedidos.setVisible(true);
                        jTablePedidos.setVisible(true);
                    }
                } catch (Exception ex) {
                    mostrarError("Error al mostrar la lista de pedidos.");
                }
            }
        } else{
            mostrarError("Introduce un nombre de usuario.");
            jScrollPanePedidos.setVisible(false);
            jTablePedidos.setVisible(false);
            jButtonRealizar.setVisible(false);
            jButtonCancelarPedido.setVisible(false);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonListarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPedidosActionPerformed
        pendientes = false;
        jTextFieldNombreCliente.setVisible(true);
        jLabelNombreCliente.setVisible(true);
        jButtonBuscar.setVisible(true);
        jTablePedidos.setVisible(false);
        jScrollPanePedidos.setVisible(false);
        jButtonRealizar.setVisible(false);
        jButtonCancelarPedido.setVisible(false);
        jButtonVolver.setVisible(true);
    }//GEN-LAST:event_jButtonListarPedidosActionPerformed

    private void jButtonRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarActionPerformed
        try {
            miControlador.completarPedidos();
        } catch (Exception ex) {
            mostrarError("Ha ocurrido un error al completar los pedidos.");
            
        }
    }//GEN-LAST:event_jButtonRealizarActionPerformed

    private void jButtonCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarPedidoActionPerformed
        try {
            miControlador.cancelarPedidos();
        } catch (Exception ex) {
            mostrarError("Ha ocurrido un error al cancelar los pedidos.");
        }
    }//GEN-LAST:event_jButtonCancelarPedidoActionPerformed

    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
        // TODO add your handling code here:
        jButtonBuscarActionPerformed(null);
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        jTextFieldNombreCliente.setVisible(false);
        jLabelNombreCliente.setVisible(false);
        jButtonBuscar.setVisible(false);
        jTablePedidos.setVisible(false);
        jScrollPanePedidos.setVisible(false);
        jButtonRealizar.setVisible(false);
        jButtonCancelarPedido.setVisible(false);
        jButtonVolver.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.DEFAULT_OPTION);
    }
    
    public void mostrarError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public JTable getjTablePedidos() {
        return jTablePedidos;
    }

    public JTextField getjTextFieldNombreCliente() {
        return jTextFieldNombreCliente;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionPedidos dialog = new GestionPedidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelarPedido;
    private javax.swing.JButton jButtonComprobarPedido;
    private javax.swing.JButton jButtonListarPedidos;
    private javax.swing.JButton jButtonRealizar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JScrollPane jScrollPanePedidos;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextField jTextFieldNombreCliente;
    // End of variables declaration//GEN-END:variables
}
