/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorRegistro;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Antonio
 */
public class RegistroUsuarios extends javax.swing.JDialog {

    private ControladorRegistro miControlador;
    /**
     * Creates new form RegistroUsuarios
     */
    public RegistroUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miControlador = new ControladorRegistro(this);
        setLocationRelativeTo(null);
      
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouppermisos = new javax.swing.ButtonGroup();
        jLabelRegistro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnombreusuario = new javax.swing.JTextField();
        jPasswordFieldusuario = new javax.swing.JPasswordField();
        jLabelnombre = new javax.swing.JLabel();
        jLabelapellidos = new javax.swing.JLabel();
        jLabeldireccion = new javax.swing.JLabel();
        jLabeltelefono = new javax.swing.JLabel();
        jTextFieldnombre = new javax.swing.JTextField();
        jTextFieldapellidos = new javax.swing.JTextField();
        jTextFielddireccion = new javax.swing.JTextField();
        jTextFieldtelefono = new javax.swing.JTextField();
        jButtonaceptar = new javax.swing.JButton();
        jButtonborrartodo = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDateChoosernacimiento = new com.toedter.calendar.JDateChooser();
        jLabeldni = new javax.swing.JLabel();
        jTextFielddni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegistro.setText("REGISTRO DE USUARIOS");
        getContentPane().add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 11, -1, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 98, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 136, -1, -1));
        getContentPane().add(jTextFieldnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 95, 157, -1));
        getContentPane().add(jPasswordFieldusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 133, 157, -1));

        jLabelnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelnombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnombre.setText("Nombre: ");
        getContentPane().add(jLabelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 174, -1, -1));

        jLabelapellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelapellidos.setText("Apellidos:");
        getContentPane().add(jLabelapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 212, -1, -1));

        jLabeldireccion.setText("Dirección:");
        getContentPane().add(jLabeldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 322, -1, -1));

        jLabeltelefono.setText("Telefono:");
        getContentPane().add(jLabeltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 363, -1, -1));
        getContentPane().add(jTextFieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 171, 157, -1));
        getContentPane().add(jTextFieldapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 209, 157, -1));
        getContentPane().add(jTextFielddireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 360, 157, -1));
        getContentPane().add(jTextFieldtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 322, 157, -1));

        jButtonaceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonaceptar.setText("Aceptar");
        jButtonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 100, 40));

        jButtonborrartodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonborrartodo.setText("Borrar todo");
        jButtonborrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonborrartodoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonborrartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 110, 40));

        jButtonsalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonsalir.setText("Salir");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 70, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fecha de nacimiento: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 284, -1, -1));

        jDateChoosernacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChoosernacimientoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChoosernacimientoKeyTyped(evt);
            }
        });
        getContentPane().add(jDateChoosernacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 284, 160, -1));

        jLabeldni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeldni.setText("DNI:");
        getContentPane().add(jLabeldni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));
        getContentPane().add(jTextFielddni, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 247, 157, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoregistro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonborrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonborrartodoActionPerformed
        jTextFieldnombreusuario.setText("");
        jPasswordFieldusuario.setText("");
        jTextFieldnombre.setText("");
        jTextFieldapellidos.setText("");
        jTextFielddireccion.setText("");
        jTextFieldtelefono.setText("");
        jDateChoosernacimiento.setDate(null);
        jTextFielddni.setText("");
    }//GEN-LAST:event_jButtonborrartodoActionPerformed

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void jDateChoosernacimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChoosernacimientoKeyPressed

    }//GEN-LAST:event_jDateChoosernacimientoKeyPressed

    private void jDateChoosernacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChoosernacimientoKeyTyped

    }//GEN-LAST:event_jDateChoosernacimientoKeyTyped

    private void jButtonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaceptarActionPerformed
        try {
            miControlador.registrar();
            this.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            if(ex.getMessage().contains("Duplicate entry") && ex.getMessage().contains("for key 'usuario'"))
                mostrarError("El usuario elegido no está disponible.");
            else if(ex.getMessage().contains("Duplicate entry") && ex.getMessage().contains("for key 'dni'"))
                mostrarError("El DNI introducido ya pertenece a un usuario.");
            else
                mostrarError("Ha ocurrido un error desconocido.\n"+ex.getMessage());
        }
    }//GEN-LAST:event_jButtonaceptarActionPerformed

    public JDateChooser getjDateChoosernacimiento() {
        return jDateChoosernacimiento;
    }

    public JPasswordField getjPasswordFieldusuario() {
        return jPasswordFieldusuario;
    }

    public JTextField getjTextFieldapellidos() {
        return jTextFieldapellidos;
    }

    public JTextField getjTextFielddireccion() {
        return jTextFielddireccion;
    }

    public JTextField getjTextFielddni() {
        return jTextFielddni;
    }

    public JTextField getjTextFieldnombre() {
        return jTextFieldnombre;
    }

    public JTextField getjTextFieldnombreusuario() {
        return jTextFieldnombreusuario;
    }

    public JTextField getjTextFieldtelefono() {
        return jTextFieldtelefono;
    }
    
    public void mostrarError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.DEFAULT_OPTION);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroUsuarios dialog = new RegistroUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrouppermisos;
    private javax.swing.JButton jButtonaceptar;
    private javax.swing.JButton jButtonborrartodo;
    private javax.swing.JButton jButtonsalir;
    private com.toedter.calendar.JDateChooser jDateChoosernacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelapellidos;
    private javax.swing.JLabel jLabeldireccion;
    private javax.swing.JLabel jLabeldni;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabeltelefono;
    private javax.swing.JPasswordField jPasswordFieldusuario;
    private javax.swing.JTextField jTextFieldapellidos;
    private javax.swing.JTextField jTextFielddireccion;
    private javax.swing.JTextField jTextFielddni;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldnombreusuario;
    private javax.swing.JTextField jTextFieldtelefono;
    // End of variables declaration//GEN-END:variables

}
